import { open } from './test.mjs';
const { browser, page, logs } = await open({ vp: { width: 844, height: 390 } });
await page.waitForFunction(() => window.__ashen, null, { timeout: 120000 });
await page.waitForTimeout(600);
const st = () => page.evaluate(() => { const A = window.__ashen; return { mode: A.GAME.mode, boss: A.boss.def.id, title: !document.getElementById('title').hidden, hud: !document.getElementById('hud').hidden, pause: !document.getElementById('pause').hidden, name: document.querySelector('#bossHud .bossName').textContent, kVis: A.BOSSES.knight.rig.root.visible, hVis: A.BOSSES.herald.rig.root.visible }; });
const out = {};
await page.click('.bossopt[data-boss="herald"]'); out.sel = await st();
await page.click('#btnContinue');
await page.evaluate(() => { window.__manual = true; const A = window.__ashen; A.CAM.t = 5; for (let i = 0; i < 60; i++) A.step(1 / 60); });
out.fight = await st();
await page.click('#btnPause'); out.paused = await st();
await page.screenshot({ path: 'shots/pause_home.png' });
await page.click('#btnHome'); await page.evaluate(() => { const A = window.__ashen; for (let i = 0; i < 20; i++) A.step(1 / 60); A.render(); });
out.home = await st();
await page.screenshot({ path: 'shots/after_home.png' });
await page.click('.bossopt[data-boss="knight"]'); await page.click('#btnContinue');
await page.evaluate(() => { const A = window.__ashen; A.CAM.t = 5; for (let i = 0; i < 60; i++) A.step(1 / 60); A.player.hp = 1; A.player.takeHit({ dmg: 999, parry: 0, gst: 0, name: 'test' }, A.player.pos.clone(), A.boss.pos); for (let i = 0; i < 60 * 3; i++) A.step(1 / 60); });
out.dead = await st(); out.fallenShown = await page.evaluate(() => !document.getElementById('fallen').hidden);
await page.click('#btnHomeF'); await page.evaluate(() => { const A = window.__ashen; for (let i = 0; i < 10; i++) A.step(1 / 60); });
out.home2 = await st();
console.log(JSON.stringify(out, null, 0));
console.log(logs.filter((l) => /error/i.test(l)).slice(0, 5).join('\n'));
await browser.close();
